version: '3'

services:
  mysql_db:
    container_name: mysql
    image: mysql:latest
    platform: linux/amd64
    environment:
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: recipe
    ports:
      - "3306:3306"
    volumes:
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d